# Generated by Django 5.0.6 on 2024-05-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_passwordresets_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresets',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
