# Generated by Django 5.0.4 on 2024-05-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_reviewer',
            field=models.BooleanField(default=False),
        ),
    ]
