# Generated by Django 5.0.4 on 2024-05-22 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PapersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title_uz', models.CharField(max_length=300)),
                ('paper_title_en', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paper_content_uz', models.TextField()),
                ('paper_content_en', models.TextField()),
                ('keywords', models.CharField(max_length=500)),
                ('article_uz', models.TextField()),
                ('article_en', models.TextField()),
                ('reference', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editions.editionmodel')),
                ('paper_cat', models.ManyToManyField(to='papers.papercategory')),
                ('views_count', models.ManyToManyField(blank=True, related_name='views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_file', models.FileField(upload_to='files/review_files')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.papersmodel')),
            ],
        ),
        migrations.AddField(
            model_name='papersmodel',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, to='papers.reviewsmodel'),
        ),
    ]
