# Generated by Django 5.0.4 on 2024-05-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditionCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_cat_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EditionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_name_uz', models.CharField(max_length=255)),
                ('edition_name_en', models.CharField(max_length=255)),
                ('edition_photo', models.ImageField(upload_to='files/editions_images')),
                ('edition_content_uz', models.TextField()),
                ('edition_content_en', models.TextField()),
                ('edition_file_uz', models.FileField(upload_to='files/edition_files')),
                ('edition_file_en', models.FileField(upload_to='files/edition_files')),
                ('edition_categories', models.ManyToManyField(to='editions.editioncategories')),
            ],
        ),
    ]
