# Generated by Django 5.0.4 on 2024-05-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editionmodel',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='editionmodel',
            name='edition_photo',
            field=models.ImageField(upload_to='editions_images'),
        ),
    ]
