# Generated by Django 5.0.4 on 2024-05-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0002_editionmodel_is_published_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editionmodel',
            old_name='edition_content',
            new_name='edition_content_en',
        ),
        migrations.RenameField(
            model_name='editionmodel',
            old_name='edition_file',
            new_name='edition_file_en',
        ),
        migrations.AddField(
            model_name='editionmodel',
            name='edition_content_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editionmodel',
            name='edition_file_uz',
            field=models.FileField(default=1, upload_to='edition_files'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editionmodel',
            name='edition_name_en',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editionmodel',
            name='edition_name_uz',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
