# Generated by Django 5.0.4 on 2024-05-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0003_rename_edition_content_editionmodel_edition_content_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editionmodel',
            name='edition_file_en',
            field=models.FileField(upload_to='files/edition_files'),
        ),
        migrations.AlterField(
            model_name='editionmodel',
            name='edition_file_uz',
            field=models.FileField(upload_to='files/edition_files'),
        ),
        migrations.AlterField(
            model_name='editionmodel',
            name='edition_photo',
            field=models.ImageField(upload_to='files/editions_images'),
        ),
    ]
