# Generated by Django 5.0.4 on 2024-05-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_title_uz', models.CharField(max_length=255)),
                ('requirement_title_en', models.CharField(max_length=255)),
                ('requirement_content_en', models.TextField()),
                ('requirement_content_uz', models.TextField()),
            ],
        ),
    ]
